--
-- pgschema database dump
--

-- Dumped from database version PostgreSQL 17.5
-- Dumped by pgschema version 1.4.0


--
-- Name: some_table; Type: TABLE; Schema: -; Owner: -
--

CREATE TABLE IF NOT EXISTS some_table (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT some_table_pkey PRIMARY KEY (id)
);

