name: Release Binary and Docker Versioned

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**.md"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-amd64
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            target: linux-arm64
            goos: linux
            goarch: arm64
          - os: macos-latest
            target: darwin-arm64
            goos: darwin
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Read version
        id: version
        run: echo "version=$(cat internal/version/VERSION)" >> $GITHUB_OUTPUT

      - name: Run tests (PostgreSQL 14)
        if: matrix.target == 'linux-amd64'
        run: |
          echo "Testing with PostgreSQL 14"
          PGSCHEMA_POSTGRES_VERSION=14 go test -v ./...

      - name: Run tests (PostgreSQL 15)
        if: matrix.target == 'linux-amd64'
        run: |
          echo "Testing with PostgreSQL 15"
          PGSCHEMA_POSTGRES_VERSION=15 go test -v ./...

      - name: Run tests (PostgreSQL 16)
        if: matrix.target == 'linux-amd64'
        run: |
          echo "Testing with PostgreSQL 16"
          PGSCHEMA_POSTGRES_VERSION=16 go test -v ./...

      - name: Run tests (PostgreSQL 17)
        if: matrix.target == 'linux-amd64'
        run: |
          echo "Testing with PostgreSQL 17"
          PGSCHEMA_POSTGRES_VERSION=17 go test -v ./...

      - name: Run tests (short)
        if: matrix.target != 'linux-amd64'
        run: go test -short -v ./...

      - name: Build binary
        run: |
          # Get git info
          GIT_COMMIT=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S")

          # Build for target platform
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build \
            -ldflags "-X github.com/pgschema/pgschema/cmd.GitCommit=${GIT_COMMIT} -X 'github.com/pgschema/pgschema/cmd.BuildDate=${BUILD_DATE}'" \
            -o pgschema-${{ matrix.target }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pgschema-${{ matrix.target }}
          path: pgschema-${{ matrix.target }}

  packages:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: echo "version=$(cat internal/version/VERSION)" >> $GITHUB_OUTPUT

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: pgschema-linux-${{ matrix.arch }}
          path: ./dist

      - name: Install nfpm
        run: |
          echo "deb [trusted=yes] https://repo.goreleaser.com/apt/ /" | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt-get update
          sudo apt-get install -y nfpm

      - name: Prepare binary
        run: |
          chmod +x ./dist/pgschema-linux-${{ matrix.arch }}
          mkdir -p ./package/usr/bin
          cp ./dist/pgschema-linux-${{ matrix.arch }} ./package/usr/bin/pgschema
          mkdir -p ./package/usr/share/doc/pgschema
          cp LICENSE ./package/usr/share/doc/pgschema/

      - name: Create nfpm config
        run: |
          cat > nfpm.yaml <<EOF
          name: pgschema
          arch: ${{ matrix.arch }}
          platform: linux
          version: ${{ steps.version.outputs.version }}
          section: database
          priority: optional
          maintainer: Bytebase <support@bytebase.com>
          description: |
            PostgreSQL declarative schema migration tool.
            Think of it as Terraform for your Postgres schemas - declare your desired state,
            generate plan, preview changes, and apply them with confidence.
          vendor: Bytebase
          homepage: https://www.pgschema.com
          license: Apache-2.0
          contents:
            - src: ./package/usr/bin/pgschema
              dst: /usr/bin/pgschema
              file_info:
                mode: 0755
            - src: ./package/usr/share/doc/pgschema/LICENSE
              dst: /usr/share/doc/pgschema/LICENSE
              file_info:
                mode: 0644
          rpm:
            group: Applications/Databases
            summary: PostgreSQL declarative schema migration tool
          EOF

      - name: Build DEB package
        run: nfpm package --packager deb --target ./dist/

      - name: Build RPM package
        run: nfpm package --packager rpm --target ./dist/

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: pgschema-deb-${{ matrix.arch }}
          path: ./dist/*.deb

      - name: Upload RPM package
        uses: actions/upload-artifact@v4
        with:
          name: pgschema-rpm-${{ matrix.arch }}
          path: ./dist/*.rpm

  release:
    needs: [build, packages]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: echo "version=$(cat internal/version/VERSION)" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries

      - name: Create release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          # go install requires tags to be prefixed with v.
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          generate_release_notes: true
          files: |
            binaries/pgschema-linux-amd64/pgschema-linux-amd64
            binaries/pgschema-linux-arm64/pgschema-linux-arm64
            binaries/pgschema-darwin-arm64/pgschema-darwin-arm64
            binaries/pgschema-deb-amd64/*.deb
            binaries/pgschema-deb-arm64/*.deb
            binaries/pgschema-rpm-amd64/*.rpm
            binaries/pgschema-rpm-arm64/*.rpm

  docker:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: docker.io
      IMAGE_NAME: pgschema/pgschema
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version
        id: version
        run: echo "version=$(cat internal/version/VERSION)" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.version.outputs.version }}

      - name: Get build info
        id: build_info
        run: |
          echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_COMMIT=${{ steps.build_info.outputs.GIT_COMMIT }}
            BUILD_DATE=${{ steps.build_info.outputs.BUILD_DATE }}
