name: Release

on:
  push:
    branches: [main]
    paths: [VERSION]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Read version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Run tests
        run: go test -v ./...

      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=darwin GOARCH=arm64 go build -o pgschema-darwin-arm64 .

      - name: Create release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          generate_release_notes: true
          files: |
            pgschema-darwin-arm64
