name: Release

on:
  push:
    branches: [main]
    paths: [VERSION]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Read version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Run tests
        run: go test -short -v ./...

      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -o pgschema-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o pgschema-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o pgschema-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o pgschema-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -o pgschema-windows-amd64.exe .
          GOOS=windows GOARCH=arm64 go build -o pgschema-windows-arm64.exe .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          generate_release_notes: true
          files: |
            pgschema-linux-amd64
            pgschema-linux-arm64
            pgschema-darwin-amd64
            pgschema-darwin-arm64
            pgschema-windows-amd64.exe
            pgschema-windows-arm64.exe